title: Divorced in Virginia
description: A practical guide to divorce in Virginia
email: divorcedinvirginia@gmail.com

# Build settings
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed

# Exclude files/folders
exclude:
  - .gitignore
  - README.md
  - node_modules
